language: node_js

node_js:
  - 10

# Travis-CI Caching
cache:
  apt: true
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'       # 更改时区
  - npm install hexo-cli -g
  - chmod +x ./travis-ci-publish.sh # 为shell文件添加可执行权限

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - ./travis-ci-publish.sh

branches:
  only:
    - hexo

env:
  global:
    - GH_REF: github.com/liuyib/liuyib.github.io.git
