# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Liuyib's Blog
subtitle: write code and love life
description: 博客，分享，开源，心得
author: liuyib
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://liuyib.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
# Set to false to remove trailing index.html from permalinks
pretty_urls:
  trailing_index: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: false
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stun

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:liuyib/liuyib.github.io.git
  branch: master

# See: https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  # icon: icon.png

# Algolia Search API Key
algolia:
  applicationID: "HVGSDQGVZB"
  apiKey: "be51eecdd830511495cc1f9c7b50f272"
  indexName: "stun_NAME"

# Local Search
search:
  path: search.json
  field: post
  content: true

# ------------------------------------
# See: https://github.com/chenzhutian/hexo-all-minifier
all_minifier: false

js_concator:
  enable: false
  bundle_path: "/js/bundle.min.js"
  front: false
  silent: false
# ------------------------------------

# See: https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml

# PWA
# See: https://github.com/lavas-project/hexo-pwa/
pwa:
  manifest:
    path: /manifest.json
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      # 缓存你的静态资源，例如你使用了 webp 格式的图片，将其添加进去
      - pattern: !!js/regexp /.*\.(js|css|html|jpg|jpeg|png|svg|gif|json|xml|eot|ttf|woff|woff2)$/
        # 缓存策略，可选值：cacheFirst, networkFirst, cacheOnly, networkOnly, fastest
        # 每个值的具体含义请查看：https://googlechromelabs.github.io/sw-toolbox/api.html#handlers
        strategy: cacheFirst
      - pattern: !!js/regexp /\//
        strategy: networkFirst
      # 如果你想缓存 CDN 资源，请像下面这样进行设置
      - pattern: !!js/regexp /raw.githubusercontent.com/
        strategy: cacheFirst
      - pattern: !!js/regexp /cdn.jsdelivr.net/
        strategy: cacheFirst
      - pattern: !!js/regexp /cdn.viglink.com/
        strategy: cacheFirst
  priority: 5
